### ISSUE TITLE
1.Loginpage - rwd2.css responsive , font issues

### ISSUE THREAD

**Issue by avinashadluri** [suryatejaadluri/webdevelopment#1]
- Dont give height in % , font in % 
- media query should not be for 120px but for 320px min width.
      FYI: https://responsivedesign.is/develop/browser-feature-support/media-queries-for-common-device-breakpoints/
- When you check in mobile and tablet, layout should be properly fit into the width. Input labels are not properly aligned.
- HTML, Css, JS code should be properly indented and naming of functions and variables should be meaningful.
- Validations are good , to be improved.
- Do not reset form if vallidations are done, just show alert.

**Comment by suryatejaadluri** [comment]
- media query issue resolved (min width:320px).

- Width of input labels in mobile and tablet is now properly fit into the width..

- Improved validation with error code to give alert box only when there is no error.

- I removed reset it will now only reset after displaying alert box.

- intendation and font size issues I will follow correctly from next assignment.
