### ISSUE TITLE
5th.step wise registration

### ISSUE THREAD

**Issue by avinashadluri** [suryatejaadluri/webdevelopment#5]
Status please...

_Sent from my Xiaomi MI MAX using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by suryatejaadluri** [comment]
In starting only building layout

**Comment by avinashadluri** [comment]
https://play.google.com/store/apps/details?id=com.fastaccess.github

_Sent from my Xiaomi MI MAX using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by suryatejaadluri** [comment]
Project 5 completed please check

_Sent from my Motorola Moto G (4) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by avinashadluri** [comment]
Sure .soon

_Sent from my Xiaomi MI MAX using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by suryatejaadluri** [comment]
What is the next step pls tell me ASAP.

_Sent from my Motorola Moto G (4) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by avinashadluri** [comment]
Will mail u tonyt!
