### ISSUE TITLE
Campus Drive ...!!

### ISSUE THREAD

**Issue by suryatejaadluri** [suryatejaadluri/webdevelopment#8]
this is where I post my queries about interviews

**Comment by avinashadluri** [comment]
Whatever the interview, below are the key points:

- Be confident
- Be Clear
- Don't be rude
- Use proper language to explain your answer/opinion
- Make sure that you are sticking to the point, without diverting
- Do not confuse self or others
- If not sure confess it, no need to be 100% right all the time
- Technical knowledge can only save you , than any other skill
- Do not create hype about your personality or subject or work.. just BE YOU!

**Comment by suryatejaadluri** [comment]
what is the difference between ctc and lpa?
